#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
##### Bar Appearance #####

sketchybar --bar position=top height=40 blur_radius=50 color="$TRANSPARENT" corner_radius=0 margin=0 y_offset=0

##### Defaults #####

default=(
	padding_left=5
	padding_right=5
	icon.font="Hack Nerd Font:Regular:18.0"
	label.font="SF Pro:Regular:15.0"
	label.color=0xffffffff
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
	sketchybar --add item space."$sid" left \
		--subscribe space."$sid" aerospace_workspace_change \
		--set space."$sid" \
		background.height=20 \
		icon.padding_left=1 icon.padding_right=1 background.drawing=off \
		click_script="aerospace workspace $sid" \
		script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Adding Left Items #####
sketchybar --add item front_app left

sketchybar --set front_app \
	background.color="$TRANSPARENT" \
	icon.font="sketchybar-app-font:Regular:17.0" \
	label.font="SF Pro:Regular:14.0" \
	script="$PLUGIN_DIR/front_app.sh"

sketchybar --subscribe front_app front_app_switched

##### Add LEFT BRACKET transparent background #####
# sketchybar --add bracket left_items space.1 space.2 space.3 space.4 space.5 space.6 space.7 space.8 front_app

sketchybar --set left_items \
	background.color="$DARK_BAR_COLOR_60" \
	background.corner_radius=50 \
	background.height=36 \
	background.padding_left=30 \
	background.padding_right=30 \
	background.margin=20

##### Adding Right Items #####
#
sketchybar --add item calendar right \
	--set calendar icon="" \
	label.font="SF Pro:Regular:14.0" \
	update_freq=50 \
	click_script="open -a Calendar" \
	script="$PLUGIN_DIR/clock.sh"

# Battery
sketchybar --add item battery right

sketchybar --set battery \
	update_freq=120 \
	script="$PLUGIN_DIR/battery.sh" \
	label.font="SF Pro:Regular:14.0"

sketchybar --subscribe battery system_woke power_source_change

#Spotify currently playing label
sketchybar --add item spotify right
sketchybar --set spotify \
	script="$HOME/.config/sketchybar/items/spotify.sh" \
	icon= \
	icon.font="Hack Nerd Font:Bold:18.0" \
	icon.color="$GREEN" \
	label.font="SF Pro:Regular:14.0" \
	update_freq=4 \
	background.padding_right=2 \
	click_script="open -a Spotify"

# sketchybar --add bracket right_items spotify volume battery calendar

sketchybar --set right_items \
	background.color="$DARK_BAR_COLOR_60" \
	background.corner_radius=50 \
	background.height=36 \
	background.padding_left=30 \
	background.padding_right=30

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
